//
// Created by beedz on 30.04.2024.
//

#ifndef MATH_MODELING_EXTRA_FUNCTIONS_FOR_COURSE_WORK_H
#define MATH_MODELING_EXTRA_FUNCTIONS_FOR_COURSE_WORK_H

#endif //MATH_MODELING_EXTRA_FUNCTIONS_FOR_COURSE_WORK_H
